In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
df=pd.read_csv('weight-height.csv')
df

Gender     Height      Weight
0       Male  73.847017  241.893563
1       Male  68.781904  162.310473
2       Male  74.110105  212.740856
3       Male  71.730978  220.042470
4       Male  69.881796  206.349801
...      ...        ...         ...
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

[10000 rows x 3 columns]

In [5]:
np.unique(df['Gender'],return_counts=True)

(array(['Female', 'Male'], dtype=object), array([5000, 5000], dtype=int64))

In [6]:
np.unique(df['Height'],return_counts=True)

(array([54.26313333, 54.61685783, 54.87372753, ..., 78.52821043,
        78.62137397, 78.99874235]),
 array([1, 1, 1, ..., 1, 1, 1], dtype=int64))

In [8]:
x=df.iloc[:,0].values
x

array(['Male', 'Male', 'Male', ..., 'Female', 'Female', 'Female'],
      dtype=object)

In [9]:
y=df.iloc[:,1].values
y

array([73.84701702, 68.78190405, 74.11010539, ..., 63.86799221,
       69.03424313, 61.94424588])

In [11]:
x=x.reshape(-1,1)
y=y.reshape(-1,1)

In [13]:
from sklearn.model_selection import train_test_split
training_x,testing_x,trainging_y,testing_y=train_test_split(x,y,test_size=0.2,random_state=0)

ModuleNotFoundError: No module named 'sklearn'